<?php

return [
  // Hành động thao tác với đơn hàng
  'order-action' => [
    'email_buy' => 'Đặt đơn hàng',
    'email_admin' => 'Gửi lại email cho khách',
    'accept' => 'Tiếp nhận đơn hàng',
    'unaccept' => 'Hủy tiếp nhận đơn hàng',
    'assign' => 'Gán tiếp nhận đơn hàng',
    'delete' => 'Xóa đơn hàng',
    'waiting-payment' => 'Chờ thanh toán',
    'confirm_delivered' => 'Xác nhận giao nhận',
    'payment' => 'Xác nhận đã thanh toán',
    'complete' => 'Hoàn thành đơn hàng',
    'refund' => 'Hoàn tiền đơn hàng',
    'cancel' => 'Hủy đơn hàng',
    'export' => 'Đơn hàng xuất kho',
    'on_devery' => 'Đơn hàng đang giao',
    'deliveried' => 'Đơn hàng đã giao thành công',
    'add' => 'Thêm mới',
    'edit' => 'Sửa thông tin hóa đơn',
    'delete' => 'Hủy hóa đơn',
    'payment' => 'Xác nhận thanh toán',
    'payment_pending' => 'Xác nhận chờ thanh toán',
    'request_refund' => 'Yêu cầu hoàn tiền',
    'confirm_refund' => 'Xác nhận hoàn tiền',
    'confirm_transport' => 'Xác nhận đang giao',
    'confirm_delivered' => 'Xác nhận đã giao hàng',
    'done_refund' => 'Hoàn thành hoàn tiền',
    'order_update_error' => 'Cập nhật đơn hàng có lỗi',
    'send_mail' => 'Gửi mail thông báo',
    'assign' => 'Gán xử lý',
    'unassign' => 'Bỏ gán xử lý',
    'email_buy' => 'Gửi email mua hàng',
    'email_admin' => 'Gửi email thông báo admin',
    'push_crm' => 'Đẩy thông tin sang CRM',
    'status_change' => 'Đổi trạng thái hóa đơn',
    'complete' => 'Hoàn thành đơn',
    'payerror' => 'Quá trình cập nhật thanh toán có lỗi!',
    'error_bot_order' => 'Tạo đơn có lỗi phía bot bán hàng!',
    'email_coupon' => 'Gửi mail Coupon',
    'error_coupon' => 'Lỗi Coupon',
    'error_coupon_getquantity' => 'Lỗi check số lượng coupon',
    'error_coupon_check_storage' => 'Lỗi khi call check storage',
    'go_to_pay_gate' => 'Chuyển hướng payment',
    'pay_gate_log_result' => 'Kết quả trả về từ PayGate',
    'not_enough' => 'Không đủ số lượng',
    'webhook_billing' => 'Webhook Billing',
    'cronjob_order_coupon' => 'Cronjob Coupon Order',
    'push_ghtk' => 'Đẩy đơn GHTK',
    'abort_ghtk' => 'Hủy đơn GHTK',
    'print_order' => 'In thông tin đơn hàng',
    'webhooking_ghtk' => 'Webhook GHTK'
  ],
  
];
